/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.life.majiang.community.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import life.majiang.community.exception.CustomizeErrorCode;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class CustomizeErrorCode_SSTest extends CustomizeErrorCode_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getCode_0()  throws Throwable  {
      CustomizeErrorCode customizeErrorCode0 = CustomizeErrorCode.SYS_ERROR;

      //invoke method for customizeErrorCode0
      customizeErrorCode0.getCode();
  }
  @Test(timeout = 4000)
  public void test_getMessage_1()  throws Throwable  {
      CustomizeErrorCode customizeErrorCode0 = CustomizeErrorCode.NO_LOGIN;

      //invoke method for customizeErrorCode0
      customizeErrorCode0.getMessage();
  }}
